language: node_js
node_js:
  - '8'
services:
  - docker
install:
  - yarn --ignore-engines
script:
  - yarn test
  - yarn build
  - docker build -t wsflare/ws-flare-graphql:$TRAVIS_BUILD_NUMBER .
deploy:
  - provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push wsflare/ws-flare-graphql
    on:
      branch: master